-- Milestone achievements: generic metric/threshold definitions evaluated by the badge service.
ALTER TABLE community_badge_definitions ADD COLUMN metric TEXT;
ALTER TABLE community_badge_definitions ADD COLUMN threshold INTEGER;
ALTER TABLE community_badge_definitions ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
UPDATE community_badge_definitions SET metric='xp',threshold=250,sort_order=20 WHERE key='community_level_5';
UPDATE community_badge_definitions SET metric='xp',threshold=1000,sort_order=21 WHERE key='community_level_10';
UPDATE community_badge_definitions SET metric='xp',threshold=4000,sort_order=22 WHERE key='community_level_20';
UPDATE community_badge_definitions SET sort_order=10 WHERE key='discord_linked';
UPDATE community_badge_definitions SET sort_order=30 WHERE key='server_booster';
UPDATE community_badge_definitions SET sort_order=40 WHERE key='first_work';
INSERT INTO community_badge_definitions(key,icon,category,titles,descriptions,created_at,metric,threshold,sort_order) VALUES
('creator_works_3','book','creation','{"zh-Hant":"三部曲","zh-Hans":"三部曲","en":"Trilogy","ja":"三部作","ko":"3부작"}','{"zh-Hant":"上架 3 張卡片。","zh-Hans":"上架 3 张卡片。","en":"List 3 cards.","ja":"カードを 3 枚掲載する。","ko":"카드 3장을 게시하세요."}',0,'works_listed',3,41),
('creator_works_10','book','creation','{"zh-Hant":"多產作者","zh-Hans":"多产作者","en":"Prolific author","ja":"多作の作者","ko":"다작 작가"}','{"zh-Hant":"上架 10 張卡片。","zh-Hans":"上架 10 张卡片。","en":"List 10 cards.","ja":"カードを 10 枚掲載する。","ko":"카드 10장을 게시하세요."}',0,'works_listed',10,42),
('creator_works_30','book','creation','{"zh-Hant":"造世者","zh-Hans":"造世者","en":"World builder","ja":"世界の創り手","ko":"세계의 창조자"}','{"zh-Hant":"上架 30 張卡片。","zh-Hans":"上架 30 张卡片。","en":"List 30 cards.","ja":"カードを 30 枚掲載する。","ko":"카드 30장을 게시하세요."}',0,'works_listed',30,43),
('creator_featured','trophy','creation','{"zh-Hant":"精選作者","zh-Hans":"精选作者","en":"Featured author","ja":"注目の作者","ko":"추천 작가"}','{"zh-Hant":"有卡片獲選為 HearthRoom 精選卡。","zh-Hans":"有卡片获选为 HearthRoom 精选卡。","en":"Have a card chosen as HearthRoom Featured.","ja":"カードが HearthRoom 注目カードに選ばれる。","ko":"카드가 HearthRoom 추천 카드로 선정되면 획득해요."}',0,'works_featured',1,44),
('creator_followers_10','users','creation','{"zh-Hant":"人氣新星","zh-Hans":"人气新星","en":"Rising star","ja":"期待の新星","ko":"떠오르는 별"}','{"zh-Hant":"被 10 位成員關注。","zh-Hans":"被 10 位成员关注。","en":"Be followed by 10 members.","ja":"10 人のメンバーにフォローされる。","ko":"멤버 10명이 팔로우하면 획득해요."}',0,'followers',10,45),
('creator_followers_100','users','creation','{"zh-Hant":"萬人迷","zh-Hans":"万人迷","en":"Crowd favorite","ja":"人気者","ko":"인기 스타"}','{"zh-Hant":"被 100 位成員關注。","zh-Hans":"被 100 位成员关注。","en":"Be followed by 100 members.","ja":"100 人のメンバーにフォローされる。","ko":"멤버 100명이 팔로우하면 획득해요."}',0,'followers',100,46),
('creator_favorited_10','heart','creation','{"zh-Hant":"有口皆碑","zh-Hans":"有口皆碑","en":"Well loved","ja":"評判の作者","ko":"사랑받는 작가"}','{"zh-Hant":"卡片累計被收藏 10 次。","zh-Hans":"卡片累计被收藏 10 次。","en":"Have your cards saved 10 times in total.","ja":"カードが合計 10 回保存される。","ko":"카드가 총 10번 저장되면 획득해요."}',0,'favorites_received',10,47),
('creator_favorited_100','heart','creation','{"zh-Hant":"典藏名家","zh-Hans":"典藏名家","en":"Collector''s choice","ja":"殿堂入り","ko":"명작 작가"}','{"zh-Hant":"卡片累計被收藏 100 次。","zh-Hans":"卡片累计被收藏 100 次。","en":"Have your cards saved 100 times in total.","ja":"カードが合計 100 回保存される。","ko":"카드가 총 100번 저장되면 획득해요."}',0,'favorites_received',100,48),
('player_first_play','compass','play','{"zh-Hant":"初次見面","zh-Hans":"初次见面","en":"First hello","ja":"はじめまして","ko":"첫 만남"}','{"zh-Hant":"第一次與角色開始對話。","zh-Hans":"第一次与角色开始对话。","en":"Start your first conversation with a character.","ja":"初めてキャラクターと会話を始める。","ko":"캐릭터와 첫 대화를 시작하세요."}',0,'cards_played',1,60),
('player_explorer_10','compass','play','{"zh-Hant":"探險家","zh-Hans":"探险家","en":"Explorer","ja":"探検家","ko":"탐험가"}','{"zh-Hant":"與 10 個不同角色對話過。","zh-Hans":"与 10 个不同角色对话过。","en":"Talk with 10 different characters.","ja":"10 体の異なるキャラクターと会話する。","ko":"서로 다른 캐릭터 10명과 대화하세요."}',0,'cards_played',10,61),
('player_explorer_50','compass','play','{"zh-Hant":"旅人","zh-Hans":"旅人","en":"Wanderer","ja":"旅人","ko":"방랑자"}','{"zh-Hant":"與 50 個不同角色對話過。","zh-Hans":"与 50 个不同角色对话过。","en":"Talk with 50 different characters.","ja":"50 体の異なるキャラクターと会話する。","ko":"서로 다른 캐릭터 50명과 대화하세요."}',0,'cards_played',50,62),
('player_saver','bookmark','play','{"zh-Hant":"存檔點","zh-Hans":"存档点","en":"Save point","ja":"セーブポイント","ko":"세이브 포인트"}','{"zh-Hant":"第一次為對話存檔。","zh-Hans":"第一次为对话存档。","en":"Save a conversation for the first time.","ja":"初めて会話をセーブする。","ko":"처음으로 대화를 저장하세요."}',0,'saves',1,63),
('player_favorites_10','heart','play','{"zh-Hant":"收藏家","zh-Hans":"收藏家","en":"Collector","ja":"コレクター","ko":"수집가"}','{"zh-Hant":"收藏 10 張卡片。","zh-Hans":"收藏 10 张卡片。","en":"Save 10 cards.","ja":"カードを 10 枚保存する。","ko":"카드 10장을 저장하세요."}',0,'favorites',10,64),
('player_favorites_50','heart','play','{"zh-Hant":"圖書館員","zh-Hans":"图书馆员","en":"Librarian","ja":"司書","ko":"사서"}','{"zh-Hant":"收藏 50 張卡片。","zh-Hans":"收藏 50 张卡片。","en":"Save 50 cards.","ja":"カードを 50 枚保存する。","ko":"카드 50장을 저장하세요."}',0,'favorites',50,65),
('player_follows_5','users','play','{"zh-Hant":"追星族","zh-Hans":"追星族","en":"Fan club","ja":"推し活","ko":"팬클럽"}','{"zh-Hant":"關注 5 位作者。","zh-Hans":"关注 5 位作者。","en":"Follow 5 creators.","ja":"5 人の作者をフォローする。","ko":"작가 5명을 팔로우하세요."}',0,'follows',5,66),
('player_commenter_1','chat','social','{"zh-Hant":"初次開口","zh-Hans":"初次开口","en":"First comment","ja":"初コメント","ko":"첫 댓글"}','{"zh-Hant":"留下第一則留言。","zh-Hans":"留下第一则留言。","en":"Leave your first comment.","ja":"初めてコメントを残す。","ko":"첫 댓글을 남기세요."}',0,'comments',1,80),
('player_commenter_10','chat','social','{"zh-Hant":"話匣子","zh-Hans":"话匣子","en":"Chatterbox","ja":"おしゃべり","ko":"수다쟁이"}','{"zh-Hant":"留下 10 則留言。","zh-Hans":"留下 10 则留言。","en":"Leave 10 comments.","ja":"コメントを 10 件残す。","ko":"댓글 10개를 남기세요."}',0,'comments',10,81),
('player_commenter_100','chat','social','{"zh-Hant":"評論家","zh-Hans":"评论家","en":"Critic","ja":"批評家","ko":"평론가"}','{"zh-Hant":"留下 100 則留言。","zh-Hans":"留下 100 则留言。","en":"Leave 100 comments.","ja":"コメントを 100 件残す。","ko":"댓글 100개를 남기세요."}',0,'comments',100,82),
('player_liked_10','spark','social','{"zh-Hant":"有人按讚","zh-Hans":"有人点赞","en":"Well said","ja":"いいねをもらった","ko":"좋아요 받음"}','{"zh-Hant":"留言累計獲得 10 個讚。","zh-Hans":"留言累计获得 10 个赞。","en":"Receive 10 likes on your comments.","ja":"コメントに合計 10 件のいいねをもらう。","ko":"댓글에 좋아요를 총 10개 받으세요."}',0,'likes_received',10,83),
('player_liked_100','spark','social','{"zh-Hant":"金句製造機","zh-Hans":"金句制造机","en":"Quotable","ja":"名言メーカー","ko":"명언 제조기"}','{"zh-Hant":"留言累計獲得 100 個讚。","zh-Hans":"留言累计获得 100 个赞。","en":"Receive 100 likes on your comments.","ja":"コメントに合計 100 件のいいねをもらう。","ko":"댓글에 좋아요를 총 100개 받으세요."}',0,'likes_received',100,84),
('member_profile','pen','member','{"zh-Hant":"自我介紹","zh-Hans":"自我介绍","en":"Introduced","ja":"自己紹介","ko":"자기소개"}','{"zh-Hant":"編輯過個人資料。","zh-Hans":"编辑过个人资料。","en":"Edit your profile.","ja":"プロフィールを編集する。","ko":"프로필을 편집하세요."}',0,'profile',1,100),
('member_founder','seedling','member','{"zh-Hant":"創站元老","zh-Hans":"创站元老","en":"Founding member","ja":"創設メンバー","ko":"창립 멤버"}','{"zh-Hant":"2026 年 10 月之前加入 HearthRoom。","zh-Hans":"2026 年 10 月之前加入 HearthRoom。","en":"Join HearthRoom before October 2026.","ja":"2026 年 10 月より前に HearthRoom に参加する。","ko":"2026년 10월 이전에 HearthRoom에 가입하면 획득해요."}',0,'founder',1,101),
('member_anniversary','clock','member','{"zh-Hant":"老朋友","zh-Hans":"老朋友","en":"One year together","ja":"一周年","ko":"1주년"}','{"zh-Hant":"加入 HearthRoom 滿一年。","zh-Hans":"加入 HearthRoom 满一年。","en":"Be a HearthRoom member for one year.","ja":"HearthRoom に参加して 1 年経つ。","ko":"HearthRoom 가입 1년이 되면 획득해요."}',0,'tenure_days',365,102);
UPDATE public_catalog_clock SET revision=lower(hex(randomblob(16))) WHERE id=1;
