import { afterEach, expect, it, vi } from 'vitest';
import { createApp, nextTick } from 'vue';
import { createPinia, setActivePinia } from 'pinia';
import { createRouter, createMemoryHistory } from 'vue-router';
import { i18n } from '../src/lib/i18n';
import { useSession } from '../src/lib/session';
import { currentProvider, setProvider } from '../src/lib/provider';
import WalletPage from '../src/pages/WalletPage.vue';
const mocks = vi.hoisted(() => ({wallet:vi.fn(),records:vi.fn(),token:vi.fn()}));
vi.mock('../src/lib/api',async original => ({...await original<typeof import('../src/lib/api')>(),fetchWallet:mocks.wallet,fetchScoreRecords:mocks.records}));
vi.mock('../src/lib/connections',()=>({accountToken:mocks.token}));
let app:ReturnType<typeof createApp>;let root:HTMLElement;
afterEach(()=>{app?.unmount();root?.remove();vi.clearAllMocks();});
it('shows both balances and histories without a global provider switch',async()=>{
  setProvider('lunatalk');
  mocks.token.mockImplementation(async p=>`token-${p}`);
  mocks.wallet.mockImplementation(async (_t,p)=>({score:p==='harbor'?222:111,tempScore:0,plans:[]}));
  mocks.records.mockImplementation(async (_t,_page,_size,p)=>({records:[{id:1,record:`${p} entry`,score:5,recordType:'sub',createTime:'2026-09-20T00:00:00Z'}],total:1}));
  const pinia=createPinia();setActivePinia(pinia);
  const session=useSession();session.me={accountNumId:1,nickName:'Fixture',avatar:''};session.profile={identities:[{provider:'lunatalk',externalId:1},{provider:'harbor',externalId:2}]} as any;
  const router=createRouter({history:createMemoryHistory(),routes:[{path:'/wallet',component:WalletPage}]});await router.push('/wallet');
  root=document.createElement('div');document.body.append(root);app=createApp(WalletPage).use(pinia).use(router).use(i18n);app.mount(root);
  for(let i=0;i<40;i++)await Promise.resolve();await nextTick();
  expect(root.textContent).toContain('111');expect(root.textContent).toContain('222');
  expect(root.textContent).toContain('lunatalk entry');expect(root.textContent).toContain('harbor entry');
  expect(root.querySelector('a[href*="provider="]')).toBeNull();
  for(const button of root.querySelectorAll('.seg button'))button.dispatchEvent(new MouseEvent('click',{bubbles:true}));
  expect(currentProvider()).toBe('lunatalk');
  expect(mocks.token).toHaveBeenCalledWith('harbor',2);
});
