import { afterEach, expect, it, vi } from 'vitest';
import { createApp, nextTick } from 'vue';
import { createPinia, setActivePinia } from 'pinia';
import { createMemoryHistory, createRouter } from 'vue-router';
import { i18n } from '../src/lib/i18n';
import { useSession } from '../src/lib/session';
import { currentProvider, setProvider } from '../src/lib/provider';
import PlayPage from '../src/pages/PlayPage.vue';
const mocks=vi.hoisted(()=>({stage:vi.fn(),token:vi.fn(),authorize:vi.fn(),connect:vi.fn()}));
vi.mock('../src/lib/stage-host',()=>({ensureStage:mocks.stage,remergeStageMessages:vi.fn(),stageToasts:{list:[]}}));
vi.mock('../src/lib/connections',()=>({accountToken:mocks.token,connectAccount:mocks.connect}));
vi.mock('../src/lib/play-authorization',()=>({ensurePlayAuthorization:mocks.authorize}));
vi.mock('../src/lib/api',async original=>({...await original<typeof import('../src/lib/api')>(),fetchMeAt:async()=>({accountNumId:22,nickName:'Second account',avatar:''})}));
let app:ReturnType<typeof createApp>;let root:HTMLElement;
afterEach(()=>{app?.unmount();root?.remove();});
it('passes the selected service credentials to the player while keeping the community session',async()=>{
 setProvider('lunatalk');mocks.token.mockResolvedValue('harbor-token');mocks.authorize.mockResolvedValue(true);mocks.stage.mockResolvedValue({template:'<div>Fixture player</div>'});
 const pinia=createPinia();setActivePinia(pinia);const session=useSession();
 session.me={accountNumId:11,nickName:'Community account',avatar:''};
 session.token={accessToken:'community-token',expiresAt:Date.now()+3600000} as any;
 session.profile={identities:[{provider:'lunatalk',externalId:11},{provider:'harbor',externalId:22}]} as any;
 const router=createRouter({history:createMemoryHistory(),routes:[{path:'/play/:roleId',component:PlayPage}]});await router.push('/play/harbor-role?provider=harbor');
 root=document.createElement('div');document.body.append(root);app=createApp(PlayPage).use(pinia).use(i18n).use(router);app.mount(root);
 for(let i=0;i<40;i++)await Promise.resolve();await nextTick();
 const options=mocks.stage.mock.calls[0]![0];
 expect(options.provider).toBe('harbor');expect(options.player.accountNumId).toBe(22);
 expect(options.currentRoleId()).toBe('harbor-role');expect(await options.accessToken()).toBe('harbor-token');
 expect(mocks.authorize).toHaveBeenCalledWith('harbor-token','/play/harbor-role?provider=harbor','harbor');
 expect(currentProvider()).toBe('lunatalk');expect(session.me.accountNumId).toBe(11);expect(session.token.accessToken).toBe('community-token');expect(mocks.connect).not.toHaveBeenCalled();
});
